name: Auto Email Test

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.zoho.com
          server_port: 587

          username: ${{ secrets.ZOHO_EMAIL }}
          password: ${{ secrets.ZOHO_APP_PASSWORD }}

          subject: "GitHub Auto Test - Every 5 Minutes"
          body: "This is an automated test email sent every 5 minutes."

          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.ZOHO_EMAIL }}

          secure: false
