name: Auto Email Test
on:
  schedule:
    - cron: "*/20 * * * *"   # every 20 minutes
  workflow_dispatch:
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtppro.zoho.in
          server_port: 465
          username: ${{ secrets.ZOHO_EMAIL }}
          password: ${{ secrets.ZOHO_APP_PASSWORD }}
          subject: "GitHub Auto Test - Every 20 Minutes"
          body: "This is an automated test email sent every 20 minutes."
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.ZOHO_EMAIL }}
          secure: true
